### ISSUE TITLE
openet-client package doesn't work any longer

### ISSUE THREAD

**Issue by hduonggithub** [water3d/openet-client#4]
Just copy example with my apikey. Then I got the error message: Any idea? Thanks

Traceback (most recent call last):
  File "C:\Users\hhh\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\Lib\site-packages\urllib3\connection.py", line 196, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hhh\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\Users\hhh\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\hhh\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hhh\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\Lib\site-packages\urllib3\connectionpool.py", line 490, in _make_request
    raise new_e
  File "C:\Users\hhh\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\Lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "C:\Users\hhh\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\Lib\site-packages\urllib3\connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "C:\Users\hhh\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\Lib\site-packages\urllib3\connection.py", line 615, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\hhh\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\Lib\site-packages\urllib3\connection.py", line 205, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x000001BF7EF457D0>, 'Connection to openet.dri.edu timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\hhh\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\hhh\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\Lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hhh\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='openet.dri.edu', port=443): Max retries exceeded with url: /raster/export (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001BF7EF457D0>, 'Connection to openet.dri.edu timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hhh\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\Lib\site-packages\openet_client\raster.py", line 149, in export
    result = self.client.send_request(endpoint, method="post", **params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hhh\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\Lib\site-packages\openet_client\client.py", line 101, in send_request
    result = requester(url, headers={"Authorization": self.token}, data=body, **extra_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hhh\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\Lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hhh\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hhh\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hhh\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hhh\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\Lib\site-packages\requests\adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='openet.dri.edu', port=443): Max retries exceeded with url: /raster/export (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001BF7EF457D0>, 'Connection to openet.dri.edu timed out. (connect timeout=None)'))

**Comment by nickrsan** [comment]
Hi, yes, that's correct - this codebase no longer works with their API due to updates they made. We were looking for other contributors to help modernize it, but I no longer work at UC Merced where I built this package and likely will not return to this package in the near future. If you need bulk access to OpenET's data, you can also try https://github.com/water3d/eedl, which can download data in bulk from Earth Engine, though it's more complicated to work with.
